[package]
name = "touchgate-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
zbus = { version = "5", default-features = false, features = ["blocking-api", "async-io"] }
notify-rust = { version = "4", default-features = false, features = ["z"] }
